# Generated by Django 3.2.4 on 2021-06-18 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WController',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('WaterStart', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('WaterStop', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('refresh', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('water', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField(default=False)),
                ('old', models.TextField(default='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='TController',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('vstart', models.DecimalField(decimal_places=1, default=35.0, max_digits=3)),
                ('vstop', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('hstart', models.DecimalField(decimal_places=1, default=15.0, max_digits=3)),
                ('hstop', models.DecimalField(decimal_places=1, default=25.0, max_digits=3)),
                ('tmin', models.DecimalField(decimal_places=1, default=10.0, max_digits=3)),
                ('tmax', models.DecimalField(decimal_places=1, default=38.0, max_digits=3)),
                ('refresh', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('t', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('status', models.BooleanField(default=False)),
                ('old', models.TextField(default='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='LController',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('LightDayStart', models.TimeField(default='8:00')),
                ('LightDayStop', models.TimeField(default='20:00')),
                ('refresh', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('light', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.BooleanField(default=False)),
                ('old', models.TextField(default='')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.greenhouse')),
            ],
        ),
    ]
